import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Use',
  description:
    'Terms of Use for Sushaasan — an independent civic-technology platform. Acceptable use, content rules, disclaimers, grievance redressal, and governing law.',
}

const UPDATED = 'June 2026'

const SECTIONS: { id: string; title: string; body: React.ReactNode }[] = [
  {
    id: 'what-sushaasan-is',
    title: '1. What Sushaasan is — and is not',
    body: (
      <>
        Sushaasan (&ldquo;the Platform&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) is an{' '}
        <b>independent civic-technology initiative</b> that uses AI to organise publicly available
        information and citizen reports about civic issues into ward-level intelligence and
        indicative solution briefs for the Pune area.
        <br />
        <br />
        <b>
          Sushaasan is NOT affiliated with, endorsed by, sponsored by, or operated by the Pune
          Municipal Corporation (PMC), the Government of Maharashtra, the Government of India, or any
          public authority.
        </b>{' '}
        We are not a government grievance portal, a complaint-redressal authority, or an emergency
        service. Filing a report on Sushaasan is <b>not</b> a substitute for a formal complaint to
        PMC, the police, or any statutory body. For emergencies, contact 112.
      </>
    ),
  },
  {
    id: 'eligibility',
    title: '2. Eligibility & acceptance',
    body: (
      <>
        By accessing or using the Platform you agree to these Terms and our{' '}
        <Link href="/privacy" className="underline">Privacy Policy</Link>. You must be at least 18
        years old, or use the Platform under the supervision of a parent or legal guardian. If you do
        not agree, please do not use the Platform.
      </>
    ),
  },
  {
    id: 'acceptable-use',
    title: '3. Acceptable use & prohibited content',
    body: (
      <>
        When submitting a report or any content, you agree <b>not</b> to post anything that:
        <ul className="list-disc pl-5 mt-2 space-y-1">
          <li>is false, misleading, fabricated, or a knowingly fake report;</li>
          <li>defames, harasses, threatens, or makes personal allegations against any named individual or official;</li>
          <li>contains another person&rsquo;s private information (phone numbers, addresses, ID numbers, vehicle plates);</li>
          <li>is obscene, hateful, incites violence, or promotes enmity between groups;</li>
          <li>infringes intellectual property, or violates any law in force in India;</li>
          <li>impersonates any person or authority, or misrepresents your affiliation.</li>
        </ul>
        <span className="block mt-2">
          This list mirrors the due-diligence obligations under the Information Technology
          (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021. We may remove content
          and restrict access at our discretion to comply with the law.
        </span>
      </>
    ),
  },
  {
    id: 'your-content',
    title: '4. Your content & licence',
    body: (
      <>
        You retain ownership of what you submit. By submitting, you grant Sushaasan a non-exclusive,
        royalty-free licence to process, anonymise, aggregate, translate, and publicly display your
        report in <b>anonymised and aggregated form</b> for the civic purpose of the Platform. We do
        not publish your identity. We may share aggregated, ward-level intelligence with PMC ward
        offices. You are solely responsible for the content you submit and confirm you have the right
        to share it.
      </>
    ),
  },
  {
    id: 'ai-disclaimer',
    title: '5. AI-generated content — accuracy disclaimer',
    body: (
      <>
        Issue summaries, severity scores, cost estimates, timelines, and solution briefs on the
        Platform are <b>generated by artificial intelligence</b> from aggregated public signal and
        citizen reports. They are <b>indicative and advisory only</b>. They may contain errors,
        omissions, or outdated information, and are <b>not</b> official records, engineering
        certifications, budget commitments, legal advice, or government decisions. Do not rely on
        them as a sole basis for any action. Verify independently before acting.
      </>
    ),
  },
  {
    id: 'no-liability',
    title: '6. Disclaimer of warranties & limitation of liability',
    body: (
      <>
        The Platform is provided on an <b>&ldquo;as is&rdquo; and &ldquo;as available&rdquo;</b>{' '}
        basis without warranties of any kind. To the maximum extent permitted by law, Sushaasan, its
        founders and contributors shall not be liable for any indirect, incidental, or consequential
        loss arising from use of, or reliance on, the Platform or its content, including any decision
        taken on the basis of AI-generated briefs or citizen reports.
      </>
    ),
  },
  {
    id: 'third-party',
    title: '7. Public sources & third-party content',
    body: (
      <>
        The Platform analyses content that is already publicly visible on third-party services
        (social media, maps, news). We respect robots.txt and do not access content behind a login.
        Sushaasan does not endorse, and is not responsible for, the accuracy of third-party content
        or the views expressed by contributors. Links to external sites are provided for convenience
        only.
      </>
    ),
  },
  {
    id: 'grievance',
    title: '8. Grievance redressal (IT Rules, 2021)',
    body: (
      <>
        In accordance with Rule 3(2) of the Information Technology (Intermediary Guidelines and
        Digital Media Ethics Code) Rules, 2021, the Grievance Officer for the Platform is:
        <div className="mt-3 rounded-xl border border-ink/10 bg-white p-4 text-[13px] leading-relaxed">
          <div><b>Grievance Officer:</b> the Sushaasan team</div>
          <div><b>Email:</b> <a href="mailto:grievance@sushaasan.in" className="underline">grievance@sushaasan.in</a></div>
          <div><b>Address:</b> Pune, Maharashtra, India</div>
        </div>
        <span className="block mt-3">
          You may report any content that violates these Terms or your rights. We will{' '}
          <b>acknowledge your complaint within 24 hours</b> and{' '}
          <b>resolve it within 15 days</b> of receipt. Content that a court or authorised government
          agency orders to be removed will be taken down within the timelines required by law.
        </span>
      </>
    ),
  },
  {
    id: 'changes',
    title: '9. Changes & termination',
    body: (
      <>
        We may update these Terms from time to time; material changes will be reflected by the
        &ldquo;last updated&rdquo; date. We may suspend or restrict access to any user who breaches
        these Terms or applicable law. Continued use after changes constitutes acceptance.
      </>
    ),
  },
  {
    id: 'governing-law',
    title: '10. Governing law & jurisdiction',
    body: (
      <>
        These Terms are governed by the laws of India. Any dispute shall be subject to the exclusive
        jurisdiction of the competent courts at <b>Pune, Maharashtra</b>. Where any provision is held
        unenforceable, the remaining provisions continue in effect.
      </>
    ),
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-paper text-ink">
      <header className="sticky top-0 z-30 border-b border-ink/10 bg-white/90 backdrop-blur-sm">
        <div className="max-w-3xl mx-auto px-5 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg bg-saffron flex items-center justify-center
                            text-white font-serif font-bold text-sm">स</div>
            <span className="font-serif text-lg font-semibold text-ink">Sushaasan</span>
            <span className="text-ink/20 mx-1 hidden sm:inline">/</span>
            <span className="text-ink-2 text-sm hidden sm:inline">Terms of Use</span>
          </Link>
          <Link href="/" className="text-[11px] font-medium text-ink-3 hover:text-ink transition-colors">
            ← Back to map
          </Link>
        </div>
      </header>

      <div className="max-w-3xl mx-auto px-5 py-12 space-y-10">
        <section className="space-y-3">
          <div className="text-[9px] font-bold tracking-[0.22em] uppercase text-saffron-dark">
            Legal · please read
          </div>
          <h1 className="font-serif text-4xl sm:text-5xl font-semibold text-ink leading-[1.05]">
            Terms of Use
          </h1>
          <p className="text-ink-2 text-base leading-relaxed">
            Plain-language terms for using Sushaasan. The short version: we&rsquo;re an independent
            civic-tech platform (not a government body), our AI briefs are indicative not official,
            and we have a grievance officer you can reach any time.
          </p>
          <p className="text-[12px] text-ink-3 font-medium">Last updated: {UPDATED}</p>
        </section>

        <div className="space-y-6">
          {SECTIONS.map((s) => (
            <section key={s.id} id={s.id}
                     className="bg-white rounded-2xl border border-ink/8 shadow-sm p-6 space-y-2">
              <h2 className="font-serif text-lg font-semibold text-ink leading-tight">{s.title}</h2>
              <div className="text-[13.5px] text-ink-2 leading-relaxed">{s.body}</div>
            </section>
          ))}
        </div>

        <footer className="border-t border-ink/10 pt-8 pb-4 space-y-3 text-center">
          <div className="flex flex-wrap items-center justify-center gap-3">
            <Link href="/privacy" className="text-[11px] font-medium px-3 py-1.5 rounded-full bg-white border border-ink/10 text-ink-2 hover:border-ink/20">Privacy Policy</Link>
            <Link href="/ethics" className="text-[11px] font-medium px-3 py-1.5 rounded-full bg-white border border-ink/10 text-ink-2 hover:border-ink/20">Ethics &amp; Methodology</Link>
            <Link href="/about" className="text-[11px] font-medium px-3 py-1.5 rounded-full bg-white border border-ink/10 text-ink-2 hover:border-saffron/30">About</Link>
          </div>
          <p className="text-[11px] text-ink-3">Sushaasan · Pune, Maharashtra, India</p>
        </footer>
      </div>
    </div>
  )
}
