import { NextResponse } from 'next/server'
import { isSupabaseConfigured, createServerClient } from '@/lib/supabase'

export const dynamic = 'force-dynamic'

/**
 * GET /api/health
 * Public pipeline health check — returns row counts and last pipeline run.
 * Used for autonomous monitoring without requiring auth.
 */
export async function GET() {
  const supabaseReady = isSupabaseConfigured()

  if (!supabaseReady) {
    return NextResponse.json({
      status: 'seed-mode',
      message: 'Supabase not configured — running on seed data',
      supabase: false,
      pipeline: null,
      counts: null,
    })
  }

  try {
    const db = createServerClient()

    const [
      { count: rawPosts },
      { count: posts },
      { count: clusters },
      { count: solutions },
      { data: lastRun },
    ] = await Promise.all([
      db.from('raw_posts').select('*', { count: 'exact', head: true }),
      db.from('posts').select('*', { count: 'exact', head: true }),
      db.from('clusters').select('*', { count: 'exact', head: true }),
      db.from('solutions').select('*', { count: 'exact', head: true }),
      db.from('pipeline_runs')
        .select('id, trigger_type, status, posts_scraped, completed_at, triggered_at')
        .order('triggered_at', { ascending: false })
        .limit(1)
        .maybeSingle(),
    ])

    const pipelineHealthy = (rawPosts ?? 0) > 0
    const classifyHealthy = (posts ?? 0) > 0
    const solutionsHealthy = (solutions ?? 0) > 0

    return NextResponse.json({
      status: pipelineHealthy ? 'live' : 'idle',
      supabase: true,
      counts: {
        raw_posts: rawPosts ?? 0,
        posts: posts ?? 0,
        clusters: clusters ?? 0,
        solutions: solutions ?? 0,
      },
      pipeline: lastRun ?? null,
      checks: {
        scraping: pipelineHealthy ? '✅ raw_posts populated' : '⏳ no scraped data yet — cron fires at 03:30 UTC',
        classification: classifyHealthy ? '✅ posts classified by Claude' : '⏳ waiting for first classify run',
        solutions: solutionsHealthy ? '✅ solutions generated by Opus' : '⏳ runs Sunday 21:00 IST',
      },
      timestamp: new Date().toISOString(),
    })
  } catch (err) {
    return NextResponse.json({
      status: 'error',
      error: String(err),
      supabase: true,
      timestamp: new Date().toISOString(),
    }, { status: 500 })
  }
}
