import { NextResponse } from 'next/server'
import { isSupabaseConfigured, createServerClient } from '@/lib/supabase'

export const dynamic = 'force-dynamic'

/**
 * GET /api/health
 * Public pipeline health check — returns row counts and last pipeline run.
 * Used for autonomous monitoring without requiring auth.
 */
export async function GET() {
  const supabaseReady = isSupabaseConfigured()

  if (!supabaseReady) {
    return NextResponse.json({
      status: 'seed-mode',
      message: 'Supabase not configured — running on seed data',
      supabase: false,
      pipeline: null,
      counts: null,
    })
  }

  try {
    const db = createServerClient()
    const since24h = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString()

    const [
      { count: rawPosts },
      { count: posts },
      { count: clusters },
      { count: solutions },
      { count: rawPosts24h },
      { count: posts24h },
      { data: lastRun },
    ] = await Promise.all([
      db.from('raw_posts').select('*', { count: 'exact', head: true }),
      db.from('posts').select('*', { count: 'exact', head: true }),
      db.from('clusters').select('*', { count: 'exact', head: true }),
      db.from('solutions').select('*', { count: 'exact', head: true }),
      // Throughput in the last 24h — distinguishes "keeping pace" from "stalled"
      db.from('raw_posts').select('*', { count: 'exact', head: true }).gte('scraped_at', since24h),
      db.from('posts').select('*', { count: 'exact', head: true }).gte('created_at', since24h),
      db.from('pipeline_runs')
        .select('id, trigger_type, status, posts_scraped, completed_at, triggered_at, errors')
        .order('triggered_at', { ascending: false })
        .limit(1)
        .maybeSingle(),
    ])

    const pipelineHealthy = (rawPosts ?? 0) > 0
    const classifyHealthy = (posts ?? 0) > 0
    const solutionsHealthy = (solutions ?? 0) > 0

    // Did classification keep pace with the most recent scrape? Compare last-24h
    // throughput: if raw posts landed but few/none were classified, the Inngest
    // worker is lagging even though the visible product (clusters) is unaffected.
    const r24 = rawPosts24h ?? 0
    const p24 = posts24h ?? 0
    const classifyKeepingPace = r24 === 0 ? null : p24 >= Math.floor(r24 * 0.5)

    // Last authority-brief dispatch (best-effort — table may not exist yet).
    // Lets a monitor see when briefs last went out and on which channel.
    type DispatchRow = { dispatched_at: string; channel: string }
    let lastDispatch: DispatchRow | null = null
    try {
      const { data: dl } = await db
        .from('dispatch_log')
        .select('dispatched_at, channel')
        .order('dispatched_at', { ascending: false })
        .limit(1)
      lastDispatch = (dl?.[0] as DispatchRow | undefined) ?? null
    } catch { /* dispatch_log not migrated yet */ }

    // Per-source yield from the most recent run — lets a monitor spot a single
    // scraper (Apify actor / token) that has silently died while the others
    // still return data. A source stuck at 0 across runs needs attention.
    const lastRunRow = lastRun as
      | { posts_scraped?: number; errors?: { by_source?: Record<string, number> } }
      | null
    const bySource = lastRunRow?.errors?.by_source ?? null
    const lastRunScraped = lastRunRow?.posts_scraped ?? null
    const deadSources = bySource
      ? Object.entries(bySource).filter(([, n]) => !(n > 0)).map(([s]) => s)
      : []

    return NextResponse.json({
      status: pipelineHealthy ? 'live' : 'idle',
      supabase: true,
      counts: {
        raw_posts: rawPosts ?? 0,
        posts: posts ?? 0,
        clusters: clusters ?? 0,
        solutions: solutions ?? 0,
      },
      last_24h: {
        raw_posts_scraped: r24,
        posts_classified: p24,
        classification_keeping_pace: classifyKeepingPace,
      },
      // Yield of the most recent scrape run. last_run_scraped === 0 means every
      // Apify actor + Reddit returned nothing (token expired / actors broken) —
      // an unambiguous "scraper is down" signal, distinct from a quiet day where
      // posts are scraped but dedup drops them as already-seen.
      scrape: {
        last_run_scraped: lastRunScraped,
        by_source: bySource,
        dead_sources: deadSources,
      },
      dispatch: {
        last_dispatched_at: lastDispatch?.dispatched_at ?? null,
        last_channel: lastDispatch?.channel ?? null,
      },
      pipeline: lastRun ?? null,
      checks: {
        scraping: pipelineHealthy ? '✅ raw_posts populated' : '⏳ no scraped data yet — cron fires at 03:30 UTC',
        classification: classifyHealthy
          ? (classifyKeepingPace === false
              ? `⚠️ posts exist but classification lagging (${p24}/${r24} in last 24h) — Inngest worker may be down`
              : '✅ posts classified by Claude')
          : '⏳ waiting for first classify run',
        solutions: solutionsHealthy ? '✅ solutions generated by Opus' : '⏳ runs Sunday 21:00 IST',
      },
      timestamp: new Date().toISOString(),
    })
  } catch (err) {
    return NextResponse.json({
      status: 'error',
      error: String(err),
      supabase: true,
      timestamp: new Date().toISOString(),
    }, { status: 500 })
  }
}
