import Link from 'next/link'

/**
 * Legal disclaimer used across the product. The single most important protection
 * against being mistaken for an official government channel (impersonation),
 * and against defamation/misinformation liability for AI- and citizen-generated
 * content. Required prominently on public surfaces.
 */

// One-line version for footers.
export function DisclaimerLine({ className = '' }: { className?: string }) {
  return (
    <p className={`text-[10.5px] leading-relaxed text-ink-3 ${className}`}>
      <span className="font-semibold text-ink-2">Independent civic-technology platform.</span>{' '}
      Not affiliated with, endorsed by, or operated by the Pune Municipal Corporation or any
      government body. Issues and solution briefs are AI-generated from public information and
      citizen reports — indicative only, not official records.{' '}
      <Link href="/terms" className="underline hover:text-ink">Terms</Link>{' · '}
      <Link href="/privacy" className="underline hover:text-ink">Privacy</Link>
    </p>
  )
}

// Boxed version for report forms / solution briefs.
export function DisclaimerBox({ variant = 'general' }: { variant?: 'general' | 'report' | 'solution' }) {
  const text =
    variant === 'report'
      ? 'By submitting, you confirm this describes a genuine civic issue, contains no false, defamatory, or personal allegations against any individual, and may be shown publicly in anonymised, aggregated form. Do not include personal data, phone numbers, or accusations against named persons.'
      : variant === 'solution'
        ? 'This brief is generated by AI from aggregated public signal and citizen reports. It is an indicative advisory for discussion — not an official government decision, budget commitment, engineering certification, or legal advice. Figures are estimates.'
        : 'Sushaasan is an independent civic-technology initiative. It is not affiliated with, endorsed by, or operated by the Pune Municipal Corporation (PMC), the Government of Maharashtra, or any public authority. Content here is AI-generated from publicly available information and citizen reports; it may be inaccurate and is not an official record.'

  return (
    <div className="rounded-xl border border-ink/10 bg-ink/[0.025] px-3.5 py-2.5">
      <p className="text-[11px] leading-relaxed text-ink-3">
        <span aria-hidden className="mr-1">ⓘ</span>{text}
      </p>
    </div>
  )
}
